### ISSUE TITLE
Audit of product Quick Save issues overwriting meta

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#1581]
This ticket is for a more comprehensive review of Quick edit saving and builds on issues .

Meta values that are overwritten by Quick Edit and need noncing correctly are (please add if you find others):
- [x] personalization options (see issue #1488 and PR #1580)
- [x] external link fields (see PR #1580)
- [x] weight units (see issue #1281)
- [x] Product will not be shipped to customer checkbox
- [x] Purchase is a donation checkbox
- [x] Notify site owner via email checkbox
- [x] Unpublish product from website
