### ISSUE TITLE
Let's get our Javascript in order

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#39]
We have many, many areas in WPeC that need to be brought up to modernity in regards to javascript.

Gary has done a brilliant job on all of the new stuff, let's achieve plugin-wide parity across the board.

Here's the big tasks for this.  Since we're new to this GitHub thing, I don't really care if these are broken out into smaller tickets or not - the reality is that it's not actually going to be a heavily resource-intensive effort.
- [x] Proper AJAX throughout the javascript files.  Gary has built an awesome WPSC AJAX API as of 3.8.9 - let's ensure this is used everywhere. (See issue #368)
- [x] Make decisions about what makes it into core JS files.  Fancy Notifications? (see [GC 296](http://code.google.com/p/wp-e-commerce/issues/detail?id=296) ) ShareThis?  Arguably, JS for these should not be in core files, rather, in plugin/theme related files. (See Issue #370)
- [x] Avoid eval() - this requires no explanation.  We're doing_this_wrong(). See [GC 486](http://code.google.com/p/wp-e-commerce/issues/detail?id=486).
- [x] Properly reference our AJAX handler.  There is no shortage of Nginx issues reported due to us using '/index.php' as an AJAX handler.  See [GC 713](http://code.google.com/p/wp-e-commerce/issues/detail?id=713)
- [x] Be no more specific than we need to be with selectors.  Naturally, some thought will need to be given here with regards to backwards compatibility as well as the new theme engine.  But we needlessly cause issues like [GC 365](http://code.google.com/p/wp-e-commerce/issues/detail?id=365). (See #371)
- [x] Now is the time to move from .live() (or livequery(), or bind() or delegate() even) to .on().  See [GC 556](http://code.google.com/p/wp-e-commerce/issues/detail?id=556).  To note, the patches there only affect .livequery() usage.
- [x] We have SO MANY javascript files that we don't need.  Not even for back compat.  Let's get rid of them. (See #372)

This would all be a brilliant start.
