### ISSUE TITLE
Integrate visitor meta with custom data API

### ISSUE THREAD

**Issue by garyc40** [wp-e-commerce/WP-e-Commerce#566]
@JeffPyeBrook has done excellent work on the meta API. Just a few more things to make it work with current customer meta API.
- [x] Prefix our meta type and data table with `wpsc_` to avoid potential collisions.
- [x] Dynamically generate code at run time is not a good idea. I've removed this code.
- [x] Generate data tables without prompting user is not a good idea. Moved all database table creation inside database upgrade routines.
- [x] We should start using $wpdb->wpsc_table_name instead of a bunch of constants.
- [x] Rename `wpsc_get_customer_meta()` to `wpsc_get_customer_data()` in order to avoid confusion.
- [x] Change the way visitor ID is generated because it has to be an integer
- [x] meta timestamp functions no longer accept callbacks as they are not considered necessary.
- [x] Have separate functions for visitor and logged-in user customer data.

Please test.
